import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "../../components/page-hero";

export const metadata: Metadata = { title: "Pricing | Paktly", description: "Paktly prelaunch pricing principles and fee transparency commitments.", alternates: { canonical: "/pricing" } };

export default function PricingPage() {
  return <><PageHero eyebrow="PRICING" title="No surprise math." description="Paktly has not finalized commercial pricing. Joining the waitlist is free and requires no payment information." /><section className="container pricing-grid"><article><span className="status-chip live">TODAY</span><h2>Prelaunch waitlist</h2><strong>$0</strong><p>Occasional product updates and potential early-access invitations.</p><ul><li>No card required</li><li>No account balance</li><li>Unsubscribe at any time</li></ul></article><article><span className="status-chip planned">PLANNED</span><h2>Expense sharing</h2><strong>Not announced</strong><p>Core trip planning and expense-sharing pricing will be published before public availability.</p><ul><li>Clear consumer price</li><li>No hidden blockchain fee language</li><li>Cancellation terms shown before purchase</li></ul></article><article><span className="status-chip future">FUTURE / CONDITIONAL</span><h2>Money movement</h2><strong>Provider-dependent</strong><p>Funding, network, foreign-exchange, card, and withdrawal costs depend on approved providers and regions.</p><ul><li>Fee shown before authorization</li><li>Provider and currency identified</li><li>No feature launched without disclosures</li></ul></article></section><section className="container principle-panel"><h2>Our pricing principles</h2><div><p><strong>Upfront:</strong> show material costs before a user commits.</p><p><strong>Comparable:</strong> separate Paktly fees from provider or network charges.</p><p><strong>Reversible where possible:</strong> explain cancellation and refund treatment clearly.</p><p><strong>Regional:</strong> never imply one price or feature is available everywhere.</p></div></section><section className="center-cta container"><h2>There is nothing to buy yet.</h2><p>Join the list to hear when a usable release and its complete pricing are available.</p><Link className="button primary" href="/#waitlist">Join the waitlist <span>→</span></Link></section></>;
}
