import type { Metadata } from "next";
import { LegalPage } from "../../components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy | Paktly", description: "How Paktly collects, uses, and protects personal information across its website and application.", alternates: { canonical: "/privacy" } };

const sections = [
  { title: "Voice and AI features", content: <><p>If you choose Speak to Paktly, microphone audio is transmitted to our contracted AI provider to produce a live transcript and a proposed action. We use the transcript and the minimum relevant plan context to resolve the request. Paktly shows a preview and requires confirmation before saving an action.</p><p>Do not speak passwords, payment-card numbers, government identifiers, health information, or other unnecessary sensitive information. Voice use is optional; the standard forms remain available. We do not include audio or transcript content in application logs or analytics, and temporary recordings are removed after processing, cancellation, or failure.</p></> },
  { title: "Who this policy covers", content: <><p>This policy covers the Paktly website, waitlist, beta application, support communications, and product research. “Paktly,” “we,” and “us” refer to the operator of this product. Operator details will be added before a public consumer launch.</p><p>Provider-sandbox, payment-card, custody, KYC, and mainnet blockchain services are not currently offered to the public; additional notices will apply before those features launch.</p></> },
  { title: "Information we collect", content: <><p>When you join the waitlist or create a beta account, we collect account and profile details, authentication identifiers, device/session records, notification preferences, invitations, plan membership, expenses, splits, settlement records, and activity needed to provide features you use. If you contact us, we collect the information needed to respond.</p><p>Our hosting and security providers may process limited technical data such as IP address, browser or device information, request time, app version, diagnostics, and security logs. We do not request seed phrases or raw private keys.</p></> },
  { title: "How we use information", content: <ul><li>Operate, secure, troubleshoot, and improve the website.</li><li>Manage the waitlist and send consented product or early-access updates.</li><li>Respond to questions, privacy requests, and security reports.</li><li>Prevent abuse, fraud, and automated submissions.</li><li>Comply with law and establish, exercise, or defend legal claims.</li></ul> },
  { title: "Legal bases", content: <p>Where laws such as the UK GDPR or EU GDPR apply, we rely on your consent for optional marketing, our legitimate interests in operating and securing a prelaunch service, steps requested by you before entering a contract, and legal obligations where applicable. You may withdraw marketing consent at any time without affecting prior lawful processing.</p> },
  { title: "How we share information", content: <><p>We may share information with contracted hosting, database, email-delivery, analytics, security, and support providers that process it for us; professional advisers; authorities when legally required; or a successor in a merger, financing, acquisition, or asset transfer.</p><p>We do not currently sell personal information. We do not currently share personal information for cross-context behavioral advertising. If this changes, we will update this policy and provide required choices before the practice begins.</p></> },
  { title: "Retention", content: <p>Waitlist records are retained until you unsubscribe, ask us to delete them, the waitlist is closed, or they are no longer needed, subject to limited legal and security retention. Support communications and security logs are retained only as long as reasonably necessary for the purpose collected. We review prelaunch data periodically and delete information that is no longer useful.</p> },
  { title: "International processing", content: <p>Providers may process information outside your state, province, or country. Where required, we will use recognized transfer safeguards. This prelaunch site is directed primarily to United States users; joining the waitlist does not guarantee availability in any country.</p> },
  { title: "Your choices and rights", content: <><p>Depending on where you live, you may have rights to access, correct, delete, restrict, object to, or obtain a copy of personal information, withdraw consent, and appeal a denied request. You may also have the right to complain to your privacy regulator.</p><p>Submit a request to <a href="mailto:privacy@paktly.io">privacy@paktly.io</a>. We may need to verify that the email address belongs to you. We will not discriminate against you for exercising a privacy right.</p></> },
  { title: "Children", content: <p>The waitlist is not directed to children under 13, and the planned financial product is intended for adults. We do not knowingly collect personal information from children. Contact us if you believe a child submitted information.</p> },
  { title: "Security", content: <p>We use administrative, technical, and organizational safeguards appropriate to a prelaunch email list, including access controls, encrypted transport, data minimization, dependency review, and logging practices designed to avoid sensitive content. No system is completely secure, and this policy is not a guarantee against every incident.</p> },
  { title: "Changes and contact", content: <><p>We may update this policy as the product, providers, or law changes. Material changes will be highlighted here and, where appropriate, communicated to waitlist members before taking effect.</p><p>Questions or requests: <a href="mailto:privacy@paktly.io">privacy@paktly.io</a>. General contact: <a href="/contact">Contact Paktly</a>.</p></> }
] as const;

export default function PrivacyPage() { return <LegalPage eyebrow="YOUR INFORMATION" title="Privacy Policy" summary="A plain-language explanation of the information Paktly processes and why." effectiveDate="September 3, 2026" sections={sections} />; }
