import type { Metadata } from "next";
import { LegalPage } from "../../components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy | Paktly", description: "How Paktly collects, uses, and protects personal information across its website and application.", alternates: { canonical: "/privacy" } };

const sections = [
  { title: "Accounts, shared plans, and Paktly Smart", content: <><p>The application uses your account information to provide authentication, profiles, saved friends, shared plans, invitations, expense splitting, tracked savings, and activity. Information you add to a shared plan is visible to its authorized members. Push notifications use your device registration and notification preferences.</p><p>If you select “I’m interested” for Paktly Smart, we save that choice with your account. You can remove your interest in the You tab. Registering interest does not create a wallet or enable financial services.</p></> },
  { title: "Account deletion", content: <p>Open You → Delete account in Paktly to initiate deletion. Apple-linked accounts require confirmation with the same Apple account. Outstanding balances do not block deletion, but shared monetary records remain under a deleted-member identity so other members’ accounting stays correct. See <a href="/account-deletion">Account deletion</a> for details and help if you cannot sign in. Removing the app or signing out does not delete your account.</p> },
  { title: "Voice and AI features", content: <><p>Speak to Paktly asks for permission before using OpenAI. Audio is sent to OpenAI for transcription, either live or after recording. The transcript, your name and account identifier, and shared-plan context may be sent to OpenAI to prepare an action. Context can include plan names, descriptions, currencies, identifiers, and member names, usernames, and email addresses. You can decline and use the standard forms instead.</p><p>Review every proposed action before confirming. Do not speak passwords, payment-card numbers, government identifiers, or unnecessary sensitive information. Share other people’s information only when you are entitled to do so. Temporary recordings on your device are removed during normal processing or cancellation; provider-side processing and retention are separate. Paktly does not promise zero retention by third-party providers. Confirmed action drafts and usage counters are stored to prevent duplicates and abuse.</p></> },
  { title: "Receipt scanning", content: <p>The current receipt scanner uses Apple Vision on your device. Receipt images are not uploaded to Paktly or OpenAI by this scanner. When you confirm an expense, the selected merchant description, amount, currency, date, payer, participants, and any notes are saved to your shared plan. Other members can see those saved details. Always review the extracted total and currency.</p> },
  { title: "Who this policy covers", content: <><p>Paktly is operated by TINKERPAL LLC. In this policy, “Paktly,” “we,” and “us” refer to TINKERPAL LLC. This policy covers the Paktly website, waitlist, beta application, support communications, and product research.</p><p>Provider-sandbox, payment-card, custody, KYC, and mainnet blockchain services are not currently offered to the public; additional notices will apply before those features launch.</p></> },
  { title: "Information we collect", content: <><p>When you join the waitlist or create a beta account, we collect account and profile details, authentication identifiers, device/session records, notification preferences, invitations, plan membership, expenses, splits, settlement records, and activity needed to provide features you use. If you contact us, we collect the information needed to respond.</p><p>Our hosting and security providers may process limited technical data such as IP address, browser or device information, request time, app version, diagnostics, and security logs. We do not request seed phrases or raw private keys.</p></> },
  { title: "How we use information", content: <ul><li>Operate, secure, troubleshoot, and improve the website.</li><li>Manage the waitlist and send consented product or early-access updates.</li><li>Respond to questions, privacy requests, and security reports.</li><li>Prevent abuse, fraud, and automated submissions.</li><li>Comply with law and establish, exercise, or defend legal claims.</li></ul> },
  { title: "Legal bases", content: <p>Where laws such as the UK GDPR or EU GDPR apply, we rely on your consent for optional marketing, our legitimate interests in operating and securing a prelaunch service, steps requested by you before entering a contract, and legal obligations where applicable. You may withdraw marketing consent at any time without affecting prior lawful processing.</p> },
  { title: "How we share information", content: <><p>We may share information with contracted hosting, database, email-delivery, analytics, security, and support providers that process it for us; professional advisers; authorities when legally required; or a successor in a merger, financing, acquisition, or asset transfer.</p><p>We do not currently sell personal information. We do not currently share personal information for cross-context behavioral advertising. If this changes, we will update this policy and provide required choices before the practice begins.</p></> },
  { title: "Retention", content: <><p>Account and shared-plan information is stored to provide the service. Account deletion removes sign-in connections and private account records and replaces identifying profile information. Shared financial amounts and internal references remain pseudonymized to preserve group accounting; this does not mean every shared record becomes anonymous. See the <a href="/account-deletion">deletion details</a>.</p><p>Backups, delivered emails, support records, provider-held data, and security logs are separate from live account deletion. Contact us for applicable retention information or a specific data request. Waitlist information can be removed by contacting privacy@paktly.io.</p></> },
  { title: "International processing", content: <p>Providers may process information outside your state, province, or country. Where required, we will use recognized transfer safeguards. This prelaunch site is directed primarily to United States users; joining the waitlist does not guarantee availability in any country.</p> },
  { title: "Your choices and rights", content: <><p>Depending on where you live, you may have rights to access, correct, delete, restrict, object to, or obtain a copy of personal information, withdraw consent, and appeal a denied request. You may also have the right to complain to your privacy regulator.</p><p>Submit a request to <a href="mailto:privacy@paktly.io">privacy@paktly.io</a>. We may need to verify that the email address belongs to you. We will not discriminate against you for exercising a privacy right.</p></> },
  { title: "Children", content: <p>The waitlist is not directed to children under 13, and the planned financial product is intended for adults. We do not knowingly collect personal information from children. Contact us if you believe a child submitted information.</p> },
  { title: "Security", content: <p>Paktly uses authenticated access, shared-plan membership checks, encrypted network transport, and logging designed to avoid credentials and sensitive request content. No system is completely secure. Do not include unnecessary sensitive information in plans, notes, receipts, or voice commands.</p> },
  { title: "Changes and contact", content: <><p>We may update this policy as the product, providers, or law changes. Material changes will be highlighted here and, where appropriate, communicated to waitlist members before taking effect.</p><p>Questions or requests: <a href="mailto:privacy@paktly.io">privacy@paktly.io</a>. General contact: <a href="/contact">Contact Paktly</a>.</p></> }
] as const;

export default function PrivacyPage() { return <LegalPage eyebrow="YOUR INFORMATION" title="Privacy Policy" summary="A plain-language explanation of the information Paktly processes and why." effectiveDate="September 7, 2026" sections={sections} />; }
