import type { Metadata } from "next";
import { LegalPage } from "../../components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy | Paktly", description: "How the Paktly prelaunch website collects, uses, and protects personal information.", alternates: { canonical: "/privacy" } };

const sections = [
  { title: "Who this policy covers", content: <><p>This policy covers the Paktly prelaunch website, waitlist, support communications, and product research. “Paktly,” “we,” and “us” refer to the operator of this prelaunch product. Operator details will be added before the consumer service launches.</p><p>This policy does not yet describe live trip accounts, payment cards, custody, KYC, or blockchain transactions because those services are not currently offered.</p></> },
  { title: "Information we collect", content: <><p>When you join the waitlist, we collect your email address, your consent choice, the policy version you accepted, and the time of signup. If you contact us, we collect the information in your message and the details needed to respond.</p><p>Our hosting and security providers may process limited technical data such as IP address, browser type, device information, request time, referring page, and security logs. We do not ask for payment credentials, government identification, passkey assertions, wallet private keys, or group financial records on this website.</p></> },
  { title: "How we use information", content: <ul><li>Operate, secure, troubleshoot, and improve the website.</li><li>Manage the waitlist and send consented product or early-access updates.</li><li>Respond to questions, privacy requests, and security reports.</li><li>Prevent abuse, fraud, and automated submissions.</li><li>Comply with law and establish, exercise, or defend legal claims.</li></ul> },
  { title: "Legal bases", content: <p>Where laws such as the UK GDPR or EU GDPR apply, we rely on your consent for optional marketing, our legitimate interests in operating and securing a prelaunch service, steps requested by you before entering a contract, and legal obligations where applicable. You may withdraw marketing consent at any time without affecting prior lawful processing.</p> },
  { title: "How we share information", content: <><p>We may share information with contracted hosting, database, email-delivery, analytics, security, and support providers that process it for us; professional advisers; authorities when legally required; or a successor in a merger, financing, acquisition, or asset transfer.</p><p>We do not currently sell personal information. We do not currently share personal information for cross-context behavioral advertising. If this changes, we will update this policy and provide required choices before the practice begins.</p></> },
  { title: "Retention", content: <p>Waitlist records are retained until you unsubscribe, ask us to delete them, the waitlist is closed, or they are no longer needed, subject to limited legal and security retention. Support communications and security logs are retained only as long as reasonably necessary for the purpose collected. We review prelaunch data periodically and delete information that is no longer useful.</p> },
  { title: "International processing", content: <p>Providers may process information outside your state, province, or country. Where required, we will use recognized transfer safeguards. This prelaunch site is directed primarily to United States users; joining the waitlist does not guarantee availability in any country.</p> },
  { title: "Your choices and rights", content: <><p>Depending on where you live, you may have rights to access, correct, delete, restrict, object to, or obtain a copy of personal information, withdraw consent, and appeal a denied request. You may also have the right to complain to your privacy regulator.</p><p>Submit a request to <a href="mailto:privacy@paktly.io">privacy@paktly.io</a>. We may need to verify that the email address belongs to you. We will not discriminate against you for exercising a privacy right.</p></> },
  { title: "Children", content: <p>The waitlist is not directed to children under 13, and the planned financial product is intended for adults. We do not knowingly collect personal information from children. Contact us if you believe a child submitted information.</p> },
  { title: "Security", content: <p>We use administrative, technical, and organizational safeguards appropriate to a prelaunch email list, including access controls, encrypted transport, data minimization, dependency review, and logging practices designed to avoid sensitive content. No system is completely secure, and this policy is not a guarantee against every incident.</p> },
  { title: "Changes and contact", content: <><p>We may update this policy as the product, providers, or law changes. Material changes will be highlighted here and, where appropriate, communicated to waitlist members before taking effect.</p><p>Questions or requests: <a href="mailto:privacy@paktly.io">privacy@paktly.io</a>. General contact: <a href="/contact">Contact Paktly</a>.</p></> }
] as const;

export default function PrivacyPage() { return <LegalPage eyebrow="YOUR INFORMATION" title="Privacy Policy" summary="A plain-language explanation of the limited information this prelaunch website collects and why." effectiveDate="August 27, 2026" sections={sections} />; }
