import type { Metadata } from "next";
import { LegalPage } from "../../components/legal-page";

export const metadata: Metadata = { title: "Financial Disclosures | Paktly", description: "Important prelaunch disclosures about Paktly's planned financial features.", alternates: { canonical: "/financial-disclosures" } };

const sections = [
  { title: "No financial service is currently offered", content: <p>Paktly is a prelaunch product preview. It does not currently accept or hold funds, transmit money, issue cards, provide bank accounts, exchange currency, execute blockchain transactions for users, provide investment services, or open SocketFi smart accounts through this website.</p> },
  { title: "Mockups are illustrative", content: <p>Dollar balances, contribution schedules, card numbers, member names, expenses, transaction states, and trip examples are fictional demonstration data. A “Trip balance” shown in a mockup is not money available to you.</p> },
  { title: "Not a bank or issuer", content: <p>Paktly is not a bank, credit union, card network, or card issuer. No banking, custody, issuing, KYC, AML, sanctions-screening, or fiat-conversion partner has been announced. References to provider categories describe planned modular architecture rather than an available partnership.</p> },
  { title: "No deposit or investment protection", content: <p>Nothing on this website is represented as an FDIC-insured deposit, SIPC-protected security, or equivalent protected account. USDC is a digital asset, not a bank deposit, and future protection, redemption, insolvency, network, smart-contract, and provider risks must be disclosed for each actual arrangement before use.</p> },
  { title: "Blockchain and smart-account plans", content: <p>The architecture contemplates Stellar USDC, TripVault contracts, CCTP, passkeys, and SocketFi smart accounts for future controlled features. These components can involve irreversible transactions, software vulnerabilities, network outages, authorization failures, destination-address errors, fees, and provider dependencies. They are not live consumer features.</p> },
  { title: "Cards and funding", content: <p>Future debit-card, bank, Apple Pay, stablecoin-linked card, and merchant-spending features depend on contracts with regulated providers, supported jurisdictions, underwriting or eligibility, identity verification, network rules, and product approval. Brand references do not mean a card program exists.</p> },
  { title: "Fees, rates, limits, and refunds", content: <p>No financial fees, exchange rates, spending limits, refund rights, or settlement times have been announced. Before any launch, the applicable interface and terms must identify material Paktly, provider, network, blockchain, foreign-exchange, withdrawal, and card charges and explain cancellation and refund treatment.</p> },
  { title: "Regional and legal limits", content: <p>No country or state has been announced for real-money availability. Product access may vary by residence, citizenship, age, sanctions status, identity-verification result, provider coverage, and law. Joining the waitlist does not establish eligibility.</p> },
  { title: "No financial advice", content: <p>Website content is general product information, not financial, investment, tax, accounting, travel, or legal advice. Do not acquire or transfer digital assets based on a mockup, roadmap, or architectural description.</p> },
  { title: "Disclosure updates", content: <p>Provider names, legal entities, licenses, safeguarding arrangements, card issuer and network, custody model, eligible regions, complaints process, and protection status will be added only after they are verified. Questions may be sent to <a href="mailto:legal@paktly.io">legal@paktly.io</a>.</p> }
] as const;

export default function FinancialDisclosuresPage() { return <LegalPage eyebrow="IMPORTANT PRELAUNCH INFORMATION" title="Financial Disclosures" summary="Planned money features are not available today. This page draws a bright line between product direction and a live regulated service." effectiveDate="August 27, 2026" sections={sections} />; }
