import type { Metadata } from "next";
import { LegalPage } from "../../components/legal-page";

export const metadata: Metadata = { title: "Terms of Use | Paktly", description: "Terms governing the Paktly prelaunch website and waitlist.", alternates: { canonical: "/terms" } };

const sections = [
  { title: "The prelaunch service", content: <><p>These Terms govern your use of the Paktly website, waitlist, support channels, and product previews. Paktly is under development. The website does not currently provide payment accounts, money transmission, custody, cards, lending, investment, foreign exchange, or blockchain transaction services.</p><p>Mockups, balances, cards, schedules, and transaction examples are illustrative and do not represent an account or an offer of a financial product.</p></> },
  { title: "Eligibility", content: <p>You must be at least 18 years old and legally able to agree to these Terms. You may not use the website where doing so is prohibited by law. Joining the waitlist does not create an account, establish priority, or guarantee eligibility, access, timing, features, pricing, or geographic availability.</p> },
  { title: "Your responsibilities", content: <ul><li>Provide an email address you control and accurate information.</li><li>Use the site only for lawful purposes and follow the Acceptable Use Policy.</li><li>Do not interfere with security, availability, or other visitors.</li><li>Do not rely on product previews to make travel, tax, legal, investment, or financial decisions.</li></ul> },
  { title: "Waitlist communications", content: <p>If you affirmatively consent, we may send prelaunch updates and invitations. You may unsubscribe using an email link or by contacting <a href="mailto:privacy@paktly.io">privacy@paktly.io</a>. Operational replies to messages you send are not marketing. Separate product terms and required disclosures will apply if accounts or financial features launch.</p> },
  { title: "Intellectual property", content: <p>The website, product concepts, text, visual design, software, and Paktly marks are owned by or licensed to the operator, subject to third-party rights. We grant you a limited, revocable, nonexclusive right to use the public website for personal, noncommercial evaluation. You may not copy the design, extract data at scale, or imply endorsement.</p> },
  { title: "Feedback", content: <p>You may send feedback voluntarily. You grant us permission to use it without restriction or compensation, but you retain ownership of any underlying material you already own. Do not submit confidential information or content you lack permission to share.</p> },
  { title: "Third-party services", content: <p>The site may link to third-party services. We do not control their availability, content, security, or privacy practices. References to future infrastructure or providers describe architectural intent, not an endorsement, partnership announcement, or confirmation of commercial availability.</p> },
  { title: "No warranties", content: <p>To the maximum extent permitted by law, the prelaunch website is provided “as is” and “as available.” We do not warrant uninterrupted operation, error-free content, product launch, feature availability, or that previews will match the final service. Nothing here excludes warranties that cannot legally be excluded.</p> },
  { title: "Limitation of liability", content: <p>To the maximum extent permitted by law, we will not be liable for indirect, incidental, special, consequential, or punitive damages, lost profits, lost data, travel losses, or decisions based on a preview. Our aggregate liability concerning this free prelaunch website will not exceed US $100. These limits do not apply where prohibited or to liability that cannot lawfully be limited.</p> },
  { title: "Suspension and changes", content: <p>We may restrict access to protect the site, comply with law, investigate abuse, or discontinue the preview. We may update these Terms prospectively. Material updates will carry a new effective date; continued use after they take effect constitutes acceptance where permitted.</p> },
  { title: "Disputes and governing rules", content: <p>Because the product operator and launch jurisdiction have not been finalized, these Terms do not impose a preselected private arbitration forum or waive rights you may have under mandatory local law. Before commercial launch, this section will be replaced with operator-specific governing-law and dispute terms reviewed for the offered jurisdictions.</p> },
  { title: "Contact", content: <p>Questions about these Terms can be sent to <a href="mailto:legal@paktly.io">legal@paktly.io</a>. See also our <a href="/privacy">Privacy Policy</a>, <a href="/acceptable-use">Acceptable Use Policy</a>, and <a href="/financial-disclosures">Financial Disclosures</a>.</p> }
] as const;

export default function TermsPage() { return <LegalPage eyebrow="THE PRELAUNCH AGREEMENT" title="Terms of Use" summary="The rules for using this website and joining the Paktly waitlist before the consumer service launches." effectiveDate="August 27, 2026" sections={sections} />; }
